name: Go

on:
  push:
    branches:
      - "master"
    paths:
      - '**.go'
      - '**.yaml'
      - '**.mod'
  pull_request:
    paths:
      - '**.go'
      - '**.yaml'
      - '**.mod'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run test
        run: make test

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella

      - name: Prepare for build
        run: |
          go build -ldflags="-X github.com/sunny0826/kubecm/cmd.kubecmVersion=${{ github.run_id }} \
          -X github.com/sunny0826/kubecm/cmd.gitCommit=${{ github.sha }} \
          -X 'github.com/sunny0826/kubecm/cmd.buildDate=${{ steps.date.outputs.date }}'" \
          -o bin/kubecm .
          
          mkdir -p .debpkg/usr/{bin,lib}
          mkdir -p .debpkg/usr/lib/kubecm/completions/{zsh,bash}
          cp -r bin/kubecm .debpkg/usr/bin/
          chmod +x .debpkg/usr/bin/kubecm
          .debpkg/usr/bin/kubecm completion bash > .debpkg/usr/lib/kubecm/completions/bash/kubecm
          .debpkg/usr/bin/kubecm completion zsh > .debpkg/usr/lib/kubecm/completions/zsh/_kubecm
          
          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          cp -r LICENSE .debpkg/DEBIAN/
          cp -r script/postinst .debpkg/DEBIAN/postinst
          cp -r script/prerm .debpkg/DEBIAN/prerm
          chmod +x .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/prerm

      - uses: jiro4989/build-deb-action@v2
        with:
          package: kubecm
          package_root: .debpkg
          maintainer: 'Xudong Guo'
          version: 'v0.18.0'
          desc: 'Manage your kubeconfig more easily.'

      - name: Run Build
        run: |
          tree .debpkg

      - uses: actions/upload-artifact@v2
        with:
          name: deb-artifact
          path: ./*.deb