name: Go

on:
  push:
    branches:
      - "master"
    paths:
      - '**.go'
      - '**.yaml'
      - '**.mod'
  pull_request:
    paths:
      - '**.go'
      - '**.yaml'
      - '**.mod'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run test
        run: make test

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella

      - name: Run Build
        run: |
          make test-build
          
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/lib/kubecm
          cp -r bin/kubecm .debpkg/usr/bin/
          chmod +x .debpkg/usr/bin/kubecm
          echo -e "a=1" > .debpkg/usr/lib/kubecm/kubecm.conf
          
          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/DEBIAN
          echo -e "echo postinst" > .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postinst

      - uses: jiro4989/build-deb-action@v2
        with:
          package: kubecm
          package_root: .debpkg
          maintainer: 'Xudong Guo'
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'git'
          desc: 'Manage your kubeconfig more easily.'

      - uses: actions/upload-artifact@v2
        with:
          name: deb-artifact
          path: .debpkg/*